import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { Providers } from "./redux/provider";

export const metadata: Metadata = {
  title: "Dipankar Interior & Exterior Solutions",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <Navbar />
          <main className="relative overflow-hidden min-h-screen bg-primary-bg">
            {children}
          </main>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
